# application.yml (Base Configuration)
spring:
  profiles:
    active: dev
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: Aba14mah?
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    schemas:
#    url: jdbc:postgresql://localhost:5432/auth_service_db
#    username: postgres
#    password: Aba14mah?
# other common properties
server:
  port: 8088
  servlet:
    context-path: /dss/api/v1/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO


# Secret key
jwt:
  secret:
    key: 8KvVu4Bn2KwBNX1MdnXY6VaRVLekVxurk3aaJxnzdCuZL6AHEL0EnnAOYLZtHWUr
  access:
    token:
      expiration: 60000 #1800000 # 30 min in milliseconds for token expiration time
  refresh:
    token:
      expiration: 604800000 # 7 days in milliseconds
