-- Table: users

-- DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_active boolean DEFAULT true,
    added_on timestamp(6) without time zone,
    is_for_delete boolean DEFAULT false,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    firstname character varying(255) COLLATE pg_catalog."default",
    inserted_by character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default",
    modified_on timestamp(6) without time zone,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS users
    OWNER to postgres;

-- Table: roles

-- DROP TABLE IF EXISTS roles;

CREATE TABLE IF NOT EXISTS roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_active boolean DEFAULT true,
    added_on timestamp(6) without time zone,
    is_for_delete boolean DEFAULT false,
    inserted_by character varying(255) COLLATE pg_catalog."default",
    modified_on timestamp(6) without time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS roles
    OWNER to postgres;

-- Table: authorities

-- DROP TABLE IF EXISTS authorities;

CREATE TABLE IF NOT EXISTS authorities
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_active boolean DEFAULT true,
    added_on timestamp(6) without time zone,
    is_for_delete boolean DEFAULT false,
    inserted_by character varying(255) COLLATE pg_catalog."default",
    modified_on timestamp(6) without time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT authorities_pkey PRIMARY KEY (id),
    CONSTRAINT uknb3atvjf9ov5d0egnuk47o5e UNIQUE (name)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS authorities
    OWNER to postgres;

-- Table: refresh_token

-- DROP TABLE IF EXISTS refresh_token;

CREATE TABLE IF NOT EXISTS refresh_token
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    expires_at timestamp(6) without time zone,
    token character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS refresh_token
    OWNER to postgres;

-- Table: roles_auth

-- DROP TABLE IF EXISTS roles_auth;

CREATE TABLE IF NOT EXISTS roles_auth
(
    role_id bigint NOT NULL,
    auth_id bigint NOT NULL,
    CONSTRAINT roles_auth_pkey PRIMARY KEY (role_id, auth_id),
    CONSTRAINT fk79v5stoa5chpdbwdoyqi2henu FOREIGN KEY (role_id)
    REFERENCES roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT fk9ct2d2yd8njorfnfxu0js5c6n FOREIGN KEY (auth_id)
    REFERENCES authorities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS roles_auth
    OWNER to postgres;

-- Table: users_roles

-- DROP TABLE IF EXISTS users_roles;

CREATE TABLE IF NOT EXISTS users_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk2o0jvgh89lemvvo17cbqvdxaa FOREIGN KEY (user_id)
    REFERENCES users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT fkj6m8fwv7oqv74fcehir1a9ffy FOREIGN KEY (role_id)
    REFERENCES roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS users_roles
    OWNER to postgres;